version: 0.0
os: linux
files:
  - source: dog-facts.py
    destination: /discord-bot/dog-facts
  - source: dog-facts-start.sh
    destination: /discord-bot/dog-facts
hooks:
  ApplicationStart:
    - location: /discord-bot/dog-facts/start-dog-facts.sh
      timeout: 30
