version: 0.0
os: linux
files:
  - source: dog-facts.py
    destination: /discord-bot/dog-facts
  - source: dogfacts.service
    destination: /etc/systemd/system
hooks:
  AfterInstall:
    - location: deployment-scripts/install-dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: deployment-scripts/start-dog-facts.sh
      timeout: 30
  ApplicationStop:
    - location: deployment-scripts/stop-dog-facts.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: deployment-scripts/validate-dog-facts.sh
      timeout: 30
      runas: root
      