version: 0.0
os: linux
files:
  - source: dog-facts.py
    destination: /discord-bot/dog-facts
hooks:
  AfterInstall:
    - location: install-dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: start-dog-facts.sh
      timeout: 30
  ApplicationStop:
    - location: stop-dog-facts.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: validate-dog-facts.sh
      timeout: 30
      runas: root
      