name: Deploy Dog Facts

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWSROLE }}
          aws-region: ${{ secrets.REGION }}
      - name: Initiate CodeDeploy
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name discord-bot \
          --deployment-group-name discord-bot_deploy-group \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
        